import React from "react";

import NavigationBar from "./NavigationBar";

import Footer from "./Footer";

function PrivacyPolicy() {
  return (
    <>
      <NavigationBar />

      <div className="privacy-policy-body">
        <p className="policy-header-1">Privacy Policy</p>
        <p className="policy-header-3">Effective date: May 30th, 2022</p>
        <p>EveniMed SRL operates the www.evenimed.ro website. </p>
        <p>
          This page informs you of our policies regarding the collection, use,
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
        </p>
        <p>
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, terms used in this Privacy Policy have the same meanings as in
          our Terms and Conditions, accessible from www.evenimed.ro.
        </p>

        <p className="policy-header-2">Definitions</p>

        <p className="policy-header-3">Personal Data</p>

        <p>
          Personal Data means data about an individual who can be identified
          from those data (or from those and other information either in our
          possession or likely to come into our possession).
        </p>

        <p className="policy-header-3">Usage Data</p>

        <p>
          Usage Data is data collected automatically either generated by the use
          of the Service or from the Service infrastructure itself (i.e., the
          duration of a page visit).
        </p>

        <p className="policy-header-3">Cookies</p>

        <p>
          Cookies are small data files that are placed on your computer or
          mobile device when you visit a website. Cookies are widely used by
          online service providers in order to (for example) make their websites
          or services work, or to work more efficiently, as well as to provide
          reporting information.
        </p>

        <p className="policy-header-3">Data Controller</p>

        <p>
          Data Controller means a person who (either alone or jointly or in
          common with other persons) determines the purposes for which and the
          manner in which any personal data are, or are to be, processed. For
          the purpose of this Privacy Policy, we are a Data Controller of your
          data.
        </p>

        <p className="policy-header-3">Data Processor (or Service Providers)</p>

        <p>
          Data Processor (or Service Provider) means any person (other than an
          employee of the Data Controller) who processes the data on behalf of
          the Data Controller. We may use the services of various Service
          Providers in order to process your data more effectively.
        </p>

        <p className="policy-header-3">Data Subject</p>

        <p>
          Data Subject is any individual who is the subject of Personal Data.
        </p>

        <p className="policy-header-3">Data User</p>

        <p>
          The User is the individual using our Service. The User corresponds to
          the Data Subject, who is the subject of Personal Data.
        </p>

        <p className="policy-header-1">Information Collection and Use</p>

        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>

        <p className="policy-header-2">Types of Data Collected</p>

        <p className="policy-header-3">Personal Data</p>

        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to: Email address First name and last
          name Phone number Address, State, Province, ZIP/Postal code, City
          Cookies and Usage Data We may use your Personal Data to respond to
          your requests, contact you with newsletters or inform you of marketing
          related events that may be of interest to you. You may opt out of
          receiving any, or all, of these communications from us by following
          the unsubscribe link or by contacting us to be removed from any email
          we send.
        </p>

        <p className="policy-header-3">Usage Data</p>

        <p>
          We may also collect information on how the Service is accessed and
          used (“Usage Data”). This Usage Data may include information such as
          your computer’s Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, unique
          device identifiers and other diagnostic data.
        </p>

        <p className="policy-header-3">Tracking & Cookies Data</p>

        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and hold certain information. Cookies are files with
          small amount of data which may include an anonymous unique identifier.
          Cookies are sent to your browser from a website and stored on your
          device. Tracking technologies also used are beacons, tags, and scripts
          to collect and track information and to improve and analyze our
          Service. You can instruct your browser to refuse all cookies or to
          indicate when a cookie is being sent. However, if you do not accept
          cookies, you may not be able to use some portions of our Service.
          Examples of Cookies we use: Session Cookies. We use Session Cookies to
          operate our Service. Preference Cookies. We use Preference Cookies to
          remember your preferences and various settings. Security Cookies. We
          use Security Cookies for security purposes.
        </p>

        <p className="policy-header-2">Use of Data</p>

        <p>
          We use the collected data for various purposes: To provide and
          maintain our Service To notify you about changes to our Service To
          allow you to participate in interactive features of our Service when
          you choose to do so To provide customer support To gather analysis or
          valuable information so that we can improve our Service To monitor the
          usage of our Service To detect, prevent and address technical issues
          To provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information
        </p>

        <p className="policy-header-2">Retention of Data</p>

        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies. We will also retain Usage Data for internal
          analysis purposes. Usage Data is generally retained for a shorter
          period of time, except when this data is used to strengthen the
          security or to improve the functionality of our Service, or we are
          legally obligated to retain this data for longer time periods.
        </p>

        <p className="policy-header-2">Transfer of Data</p>

        <p>
          Your information, including Personal Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ than those from your jurisdiction. If you are located
          outside of the United States and choose to provide information to us,
          please note that we transfer the data, including Personal Data, to the
          United States and process it there. Your consent to this Privacy
          Policy followed by your submission of such information represents your
          agreement to that transfer. We will take all steps reasonably
          necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy and no transfer of your Personal
          Data will take place to an organization or a country unless there are
          adequate controls in place including the security of your data and
          other personal information.
        </p>

        <p className="policy-header-2">Disclosure of Data</p>

        <p>
          Disclosure for Law Enforcement Under certain circumstances, we may be
          required to disclose your Personal Data if required to do so by law or
          in response to valid requests by public authorities (e.g., a court or
          a government agency). Legal Requirements We may disclose your Personal
          Data in the good faith belief that such action is necessary to: To
          comply with a legal obligation To protect and defend the rights or
          property of EveniMed SRL. To prevent or investigate possible
          wrongdoing in connection with the Service To protect the personal
          safety of users of the Service or the public To protect against legal
          liability
        </p>

        <p className="policy-header-2">Security of Data</p>

        <p>
          The security of your data is important to us, but remember that no
          method of transmission over the Internet, or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security. “Do Not Track” Signals Do Not Track (“DNT”) is a preference
          you can set in your web browser to inform websites that you do not
          want to be tracked. You can enable or disable Do Not Track by visiting
          the Preferences or Settings page of your web browser.
        </p>

        <p className="policy-header-2">Your Rights</p>

        <p>
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data. Whenever made
          possible, you can update your Personal Data by contacting us to make
          the required changes. If you wish to be informed what Personal Data we
          hold about you and if you want it to be removed from our systems,
          please contact us. In certain circumstances, you have the right: To
          access and receive a copy of the Personal Data we hold about you To
          rectify any Personal Data held about you that is inaccurate To request
          the deletion of Personal Data held about you You have the right to
          data portability for the information you provide to us. You can
          request to obtain a copy of your Personal Data in a commonly used
          electronic format so that you can manage and move it. Please note that
          we may ask you to verify your identity before responding to such
          requests.
        </p>

        <p className="policy-header-2">Service Providers</p>

        <p>
          We may employ third party companies and individuals to facilitate our
          Service (“Service Providers”), to provide the Service on our behalf,
          to perform Service-related services or to assist us in analyzing how
          our Service is used. These third parties have access to your Personal
          Data only to perform these tasks on our behalf and are obligated not
          to disclose or use it for any other purpose. Analytics We may use
          third-party Service Providers to monitor and analyze the use of our
          Service. Google Analytics is a web analytics service offered by Google
          that tracks and reports website traffic. Google uses the data
          collected to track and monitor the use of our Service. This data is
          shared with other Google services. Google may use the collected data
          to contextualize and personalize the ads of its own advertising
          network. You can opt-out of having made your activity on the Service
          available to Google Analytics by installing the Google Analytics
          opt-out browser add-on. The add-on prevents the Google Analytics
          JavaScript (ga.js, analytics.js, and dc.js) from sharing information
          with Google Analytics about visits activity. For more information on
          the privacy practices of Google, please visit the Google Privacy &
          Terms web page.
        </p>

        <p className="policy-header-2">Links To Other Sites</p>

        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click on a third party link, you will be directed to that
          third party’s site. We strongly advise you to review the Privacy
          Policy of every site you visit. We have no control over and assume no
          responsibility for the content, privacy policies or practices of any
          third party sites or services.
        </p>

        <p className="policy-header-2">Children's Privacy</p>

        <p>
          Our Service is not intended for anyone under the age of 13
          (“Children”). We do not knowingly collect personally identifiable
          information from anyone under the age of 13. If you are a parent or
          guardian and you are aware that your Children has provided us with
          Personal Data, please contact us. If we become aware that we have
          collected Personal Data from children without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>

        <p className="policy-header-2">Changes To This Privacy Policy</p>

        <p>
          We may update our Privacy Policy from time to time. You are advised to
          review this Privacy Policy periodically for any changes. Changes to
          this Privacy Policy are effective when they are posted on this page.
        </p>

        <br></br>
        <p className="privacy-reach-out">
          If you have any other questions about this privacy policy, please
          contact us!
        </p>

        <br></br>
      </div>

      <Footer />
    </>
  );
}

export default PrivacyPolicy;
